name: Workflow

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: npm audit

  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: compare versions
        id: check
        uses: CharlieHodgkinson/VersionChecker@master
        with:
          localFilePath: '/home/runner/work/featureflagtech-node/featureflagtech-node/package.json'
          publicPackageName: 'featureflagtech-node'
      - name: version info
        id: info
        run: echo "Version ${{ steps.check.outputs.publicVersion }} being updated to ${{ steps.check.outputs.localVersion}}"

  publish:
    runs-on: ubuntu-latest
    needs: [tests, version-check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: echo 'successfully published to npm'